spring:
  application:
    name: ead-course-service
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: ead-config-server

#server:
#  port: 8082
#  servlet:
#    context-path: '/ead-course/'
#
#spring:
#  application:
#    name: ead-course-service
#  datasource:
#    url:  jdbc:postgresql://localhost:5432/ead-course-v2
#    username: postgres
#    password: admin
#  jpa:
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      jdbc:
#        lob.non-contextual-creation: true
#    properties:
#      hibernate:
#        show_sql: true
#  output:
#    ansi:
#      enabled: Always
#  rabbitmq:
#    addresses: amqps://nmkvknfe:MuXOYf3ZqS9FIGqzQMPp6kufgmV2taj_@toad.rmq.cloudamqp.com/nmkvknfe
#
#
#logging:
#  level:
#    com.ead: TRACE
#    root: INFO
#    org.springframework.web: DEBUG
#    org.hibernate: INFO
#
#ead:
#  api:
#    url:
#      authuser: 'http://ead-authuser-service/ead-authuser'
#  broker:
#    exchange:
#      userEventExchange: ead.userevent
#    queue:
#      userEventQueue:
#        name: ead.userevent.ms.course
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: 'http://localhost:8761/eureka'
#  instance:
#    hostname: localhost
